# Generated by Django 5.1.4 on 2025-03-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppigdata',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
