# Generated by Django 5.1.4 on 2025-03-09 20:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_user_alter_orderitems_order'),
        ('shipping', '0002_shoppigdata_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Picked up', 'Picked up'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Delayed', 'Delayed'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_updates', to='order.order')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
